# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eba319e4859813e91fe64e07934f1a6173436c31d6bee50e36e60c3dabcbe16d2155ffe4c8c8f0d049f7ba116115e56f7ee9ebd1df6665ed6bf12c4b332cb400

test:
  secret_key_base: 48ccfe3cfe749a945760077ebed8ea076aa86c327131bfe4f7abcb03bd5b9aeabbadb02c36922d84bed0114e7975d314605dc2002542f6df0209468de34a09eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: eba319e4859813e91fe64e07934f1a6173436c31d6bee50e36e60c3dabcbe16d2155ffe4c8c8f0d049f7ba116115e56f7ee9ebd1df6665ed6bf12c4b332cb400
